# The server name to use for the custom mxc:// URIs.
# This server name will effectively be a real Matrix server, it just won't implement anything other than media.
# You must either set up .well-known delegation from this domain to this program, or proxy the domain directly to this program.
server_name: giphy.example.com
# Optionally a custom .well-known response. This defaults to `server_name:443` if empty.
well_known_response:
# Matrix server signing key to make the federation tester pass, same format as synapse's .signing.key file.
# You can generate one using `giphyproxy -generate-key`.
server_key: CHANGE ME
# Should federation authentication be enforced?
# If true, requests to the /_matrix/federation/v1/media/download/... endpoint
# will check the Authorization: X-Matrix header before redirecting.
federation_auth: false

# Hostname where the proxy should listen on
hostname: 0.0.0.0
# Port where the proxy should listen on
port: 8008

# Redirect destination. This can be changed to serve a different format.
destination: https://i.giphy.com/%s.webp
